/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.ActionEvent;
import javax.swing.UnsupportedLookAndFeelException;
import Logic.DatabaseConnection;
import Logic.PasswordUtils;


/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        right = new javax.swing.JPanel();
        top = new javax.swing.JLayeredPane();
        LOGIN_title = new javax.swing.JLabel();
        middle = new javax.swing.JLayeredPane();
        username_text = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        password_text = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        show_password_checkbox = new javax.swing.JCheckBox();
        login_button = new javax.swing.JButton();
        bottom = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        signupformbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel2.setLayout(null);

        left.setBackground(new java.awt.Color(153, 0, 0));
        left.setPreferredSize(new java.awt.Dimension(400, 500));
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/cinema icon_1.jpg"))); // NOI18N
        left.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 67, -1, -1));

        jPanel2.add(left);
        left.setBounds(0, 0, 400, 500);

        right.setBackground(new java.awt.Color(51, 51, 51));
        right.setMinimumSize(new java.awt.Dimension(400, 500));
        right.setPreferredSize(new java.awt.Dimension(400, 500));

        top.setPreferredSize(new java.awt.Dimension(400, 100));
        top.setLayout(new java.awt.BorderLayout());

        LOGIN_title.setBackground(new java.awt.Color(204, 0, 51));
        LOGIN_title.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        LOGIN_title.setForeground(new java.awt.Color(204, 0, 51));
        LOGIN_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGIN_title.setText("LOGIN");
        top.add(LOGIN_title, java.awt.BorderLayout.CENTER);

        right.add(top);

        middle.setForeground(new java.awt.Color(255, 0, 0));
        middle.setPreferredSize(new java.awt.Dimension(400, 300));
        middle.setLayout(new java.awt.FlowLayout());

        username_text.setBackground(right.getBackground());
        username_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username_text.setForeground(new java.awt.Color(255, 255, 255));
        username_text.setText("Username");
        username_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        username_text.setPreferredSize(new java.awt.Dimension(250, 40));
        middle.add(username_text);

        usernamebox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernamebox.setBorder(passwordfield.getBorder());
        usernamebox.setMinimumSize(new java.awt.Dimension(250, 20));
        usernamebox.setPreferredSize(new java.awt.Dimension(250, 40));
        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });
        middle.add(usernamebox);

        password_text.setBackground(right.getBackground());
        password_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Password");
        password_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        password_text.setPreferredSize(new java.awt.Dimension(250, 40));
        middle.add(password_text);

        passwordfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordfield.setPreferredSize(new java.awt.Dimension(250, 40));
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });
        middle.add(passwordfield);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(250, 100));

        show_password_checkbox.setBackground(right.getBackground());
        show_password_checkbox.setForeground(new java.awt.Color(255, 255, 255));
        show_password_checkbox.setText("Show Password");
        show_password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_checkboxActionPerformed(evt);
            }
        });

        login_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_button.setText("LOGIN");
        login_button.setPreferredSize(new java.awt.Dimension(100, 30));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(show_password_checkbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(login_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(0, 145, Short.MAX_VALUE)
                .addComponent(show_password_checkbox))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addComponent(show_password_checkbox)
                .addGap(18, 18, 18)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        middle.add(jLayeredPane1);

        right.add(middle);

        bottom.setPreferredSize(new java.awt.Dimension(400, 60));

        jLabel5.setText("I don't have an account");
        jLabel5.setToolTipText("");

        signupformbutton.setBackground(new java.awt.Color(51, 51, 51));
        signupformbutton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        signupformbutton.setText("SIGNUP");
        signupformbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        signupformbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupformbuttonActionPerformed(evt);
            }
        });

        bottom.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bottom.setLayer(signupformbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(signupformbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(signupformbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        right.add(bottom);

        jPanel2.add(right);
        right.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_checkboxActionPerformed
        if (show_password_checkbox.isSelected()) {
            passwordfield.setEchoChar((char) 0); // Show password
        } else {
            passwordfield.setEchoChar('*'); // Hide password (you can use '*' as well)
        }
    }//GEN-LAST:event_show_password_checkboxActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        Connection conn = DatabaseConnection.connectDB(); // Call the database connection class
        if (conn != null) {
            try {
                String username = usernamebox.getText();
                String passwordInput = new String(passwordfield.getPassword());

                // Retrieve the hashed password from the database
                String sql = "SELECT password FROM customer WHERE username=?";
                PreparedStatement pst = conn.prepareStatement(sql);
                pst.setString(1, username);
                ResultSet rs = pst.executeQuery();

                if (rs.next()) {
                    String storedHashedPassword = rs.getString("password"); // Get stored hashed password
                    String hashedInputPassword = PasswordUtils.hashPassword(passwordInput); // Hash input password

                    if (storedHashedPassword.equals(hashedInputPassword)) { // Compare hashed passwords
                        JOptionPane.showMessageDialog(null, "Login Successful!");

                        // Open the main application window
                        Homepage main = new Homepage();
                        main.setVisible(true);
                        this.dispose(); // Close login form
                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Username or Password", "Login Failed", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Username or Password", "Login Failed", JOptionPane.ERROR_MESSAGE);
                }

                conn.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Login Error: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        login_buttonActionPerformed(new java.awt.event.ActionEvent(login_button, ActionEvent.ACTION_PERFORMED, "Enter"));

    }//GEN-LAST:event_passwordfieldActionPerformed

    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        passwordfield.requestFocus();    }//GEN-LAST:event_usernameboxActionPerformed

    private void signupformbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupformbuttonActionPerformed
        // Open the Signup form
        Signup signupForm = new Signup();
        signupForm.setVisible(true);

        // Optionally, close the current login form
        this.dispose(); // Closes the current form
    }//GEN-LAST:event_signupformbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());  // Use FlatLaf
        } catch (UnsupportedLookAndFeelException ex) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGIN_title;
    private javax.swing.JLayeredPane bottom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel left;
    private javax.swing.JButton login_button;
    private javax.swing.JLayeredPane middle;
    private javax.swing.JLabel password_text;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JPanel right;
    private javax.swing.JCheckBox show_password_checkbox;
    private javax.swing.JButton signupformbutton;
    private javax.swing.JLayeredPane top;
    private javax.swing.JLabel username_text;
    private javax.swing.JTextField usernamebox;
    // End of variables declaration//GEN-END:variables
}
