/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JOptionPane;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.event.ActionEvent;
import javax.swing.UnsupportedLookAndFeelException;
import Utils.UserSession;
import dao.UserDAO;

/**
 *
 * @author ACER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        cinemaicon = new Utils.SVGIconLabel();
        right = new javax.swing.JPanel();
        top = new javax.swing.JLayeredPane();
        LOGIN_title = new javax.swing.JLabel();
        middle = new javax.swing.JLayeredPane();
        usernameframe = new javax.swing.JLayeredPane();
        username_text = new javax.swing.JLabel();
        usernamebox = new javax.swing.JTextField();
        passwordframe = new javax.swing.JLayeredPane();
        password_text = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        show_password_checkbox = new javax.swing.JCheckBox();
        loginframe = new javax.swing.JLayeredPane();
        login_button = new javax.swing.JButton();
        bottom = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        signupformbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CinemaApp - Login");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 500));

        left.setBackground(new java.awt.Color(153, 0, 0));
        left.setPreferredSize(new java.awt.Dimension(400, 500));

        cinemaicon.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout leftLayout = new javax.swing.GroupLayout(left);
        left.setLayout(leftLayout);
        leftLayout.setHorizontalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftLayout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(cinemaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );
        leftLayout.setVerticalGroup(
            leftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftLayout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(cinemaicon, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );

        cinemaicon.setSVGIcon("theater.svg",200,200);

        right.setBackground(new java.awt.Color(51, 51, 51));
        right.setMinimumSize(new java.awt.Dimension(400, 500));
        right.setPreferredSize(new java.awt.Dimension(400, 500));

        top.setPreferredSize(new java.awt.Dimension(400, 100));
        top.setLayout(new java.awt.BorderLayout());

        LOGIN_title.setBackground(new java.awt.Color(204, 0, 51));
        LOGIN_title.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        LOGIN_title.setForeground(new java.awt.Color(204, 0, 51));
        LOGIN_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LOGIN_title.setText("LOGIN");
        LOGIN_title.setPreferredSize(new java.awt.Dimension(115, 60));
        top.add(LOGIN_title, java.awt.BorderLayout.CENTER);

        right.add(top);

        middle.setForeground(new java.awt.Color(255, 0, 0));
        middle.setPreferredSize(new java.awt.Dimension(400, 300));
        middle.setLayout(new java.awt.FlowLayout());

        username_text.setBackground(right.getBackground());
        username_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username_text.setForeground(new java.awt.Color(255, 255, 255));
        username_text.setText("Username");
        username_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        username_text.setPreferredSize(new java.awt.Dimension(250, 40));

        usernamebox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernamebox.setBorder(passwordfield.getBorder());
        usernamebox.setMinimumSize(new java.awt.Dimension(250, 20));
        usernamebox.setPreferredSize(new java.awt.Dimension(250, 40));
        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });

        usernameframe.setLayer(username_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        usernameframe.setLayer(usernamebox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout usernameframeLayout = new javax.swing.GroupLayout(usernameframe);
        usernameframe.setLayout(usernameframeLayout);
        usernameframeLayout.setHorizontalGroup(
            usernameframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameframeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(usernameframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        usernameframeLayout.setVerticalGroup(
            usernameframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usernameframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(usernamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        middle.add(usernameframe);

        password_text.setBackground(right.getBackground());
        password_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Password");
        password_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        password_text.setPreferredSize(new java.awt.Dimension(250, 40));

        passwordfield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        passwordfield.setPreferredSize(new java.awt.Dimension(250, 40));
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });

        show_password_checkbox.setBackground(right.getBackground());
        show_password_checkbox.setForeground(new java.awt.Color(255, 255, 255));
        show_password_checkbox.setText("Show Password");
        show_password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_checkboxActionPerformed(evt);
            }
        });

        passwordframe.setLayer(password_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        passwordframe.setLayer(passwordfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        passwordframe.setLayer(show_password_checkbox, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout passwordframeLayout = new javax.swing.GroupLayout(passwordframe);
        passwordframe.setLayout(passwordframeLayout);
        passwordframeLayout.setHorizontalGroup(
            passwordframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordframeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(passwordframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(show_password_checkbox)
                    .addGroup(passwordframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        passwordframeLayout.setVerticalGroup(
            passwordframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordframeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_password_checkbox)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        middle.add(passwordframe);

        loginframe.setPreferredSize(new java.awt.Dimension(250, 100));

        login_button.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        login_button.setText("LOGIN");
        login_button.setPreferredSize(new java.awt.Dimension(100, 30));
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        loginframe.setLayer(login_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout loginframeLayout = new javax.swing.GroupLayout(loginframe);
        loginframe.setLayout(loginframeLayout);
        loginframeLayout.setHorizontalGroup(
            loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginframeLayout.createSequentialGroup()
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 150, Short.MAX_VALUE))
        );
        loginframeLayout.setVerticalGroup(
            loginframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginframeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        middle.add(loginframe);

        right.add(middle);

        bottom.setPreferredSize(new java.awt.Dimension(400, 60));

        jLabel5.setText("I don't have an account");
        jLabel5.setToolTipText("");

        signupformbutton.setBackground(new java.awt.Color(51, 51, 51));
        signupformbutton.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        signupformbutton.setText("SIGNUP");
        signupformbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        signupformbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupformbuttonActionPerformed(evt);
            }
        });

        bottom.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bottom.setLayer(signupformbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(signupformbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(signupformbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        right.add(bottom);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(left, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(right, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_checkboxActionPerformed
        if (show_password_checkbox.isSelected()) {
            passwordfield.setEchoChar((char) 0); // Show password
        } else {
            passwordfield.setEchoChar('*'); // Hide password (you can use '*' as well)
        }
    }//GEN-LAST:event_show_password_checkboxActionPerformed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        String username = usernamebox.getText();
        String passwordInput = new String(passwordfield.getPassword());

        UserDAO userDAO = new UserDAO();
        try {
            String userRole = userDAO.authenticateUser(username, passwordInput);

            if (userRole != null) {
                JOptionPane.showMessageDialog(null, "Login Successful!");
                UserSession.setUsername(username);
                UserSession.setRole(userRole); // Store the user's role in session

                // Open appropriate panel based on role
                if ("admin".equalsIgnoreCase(userRole)) {
                    AdminPanel adminPanel = new AdminPanel();
                    adminPanel.setVisible(true);
                } 
                    Homepage main = new Homepage();
                    main.setVisible(true);
                
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Invalid Username or Password",
                        "Login Failed", JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            userDAO.closeConnection();
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        login_buttonActionPerformed(new java.awt.event.ActionEvent(login_button, ActionEvent.ACTION_PERFORMED, "Enter"));

    }//GEN-LAST:event_passwordfieldActionPerformed

    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        passwordfield.requestFocus();    }//GEN-LAST:event_usernameboxActionPerformed

    private void signupformbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupformbuttonActionPerformed
        // Open the Signup form
        Signup signupForm = new Signup();
        signupForm.setVisible(true);

        // Optionally, close the current login form
        this.dispose(); // Closes the current form
    }//GEN-LAST:event_signupformbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            javax.swing.UIManager.setLookAndFeel(new FlatDarkLaf());  // Use FlatLaf
        } catch (UnsupportedLookAndFeelException ex) {
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LOGIN_title;
    private javax.swing.JLayeredPane bottom;
    private Utils.SVGIconLabel cinemaicon;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel left;
    private javax.swing.JButton login_button;
    private javax.swing.JLayeredPane loginframe;
    private javax.swing.JLayeredPane middle;
    private javax.swing.JLabel password_text;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JLayeredPane passwordframe;
    private javax.swing.JPanel right;
    private javax.swing.JCheckBox show_password_checkbox;
    private javax.swing.JButton signupformbutton;
    private javax.swing.JLayeredPane top;
    private javax.swing.JLabel username_text;
    private javax.swing.JTextField usernamebox;
    private javax.swing.JLayeredPane usernameframe;
    // End of variables declaration//GEN-END:variables
}
