/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import Utils.PasswordUtils;
import dao.UserDAO;

/**
 * Signup class provides a user interface for new user registration.
 * It allows users to create an account by entering username, email, phone number, and password.
 * @author ACER
 */
public class Signup extends javax.swing.JFrame {

    /**
     * Creates new form Signup
     * Initializes components and centers the form on screen.
     */
    public Signup() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        title = new javax.swing.JLayeredPane();
        signup_title = new javax.swing.JLabel();
        middle = new javax.swing.JLayeredPane();
        name = new javax.swing.JLayeredPane();
        usernamebox = new javax.swing.JTextField();
        username_text = new javax.swing.JLabel();
        email = new javax.swing.JLayeredPane();
        email_text = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        nomortelepon = new javax.swing.JLayeredPane();
        phone_number_field = new javax.swing.JTextField();
        phone_number_text = new javax.swing.JLabel();
        password = new javax.swing.JLayeredPane();
        passwordfield = new javax.swing.JPasswordField();
        password_text = new javax.swing.JLabel();
        show_password_checkbox = new javax.swing.JCheckBox();
        signup_button = new javax.swing.JButton();
        bottom = new javax.swing.JLayeredPane();
        jLabel5 = new javax.swing.JLabel();
        loginformbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CinemaApp - Signup");
        setLocation(new java.awt.Point(0, 0));
        setName("signup"); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        background.setBackground(new java.awt.Color(30, 32, 34));
        background.setMinimumSize(new java.awt.Dimension(400, 500));
        background.setPreferredSize(new java.awt.Dimension(400, 600));

        title.setMinimumSize(new java.awt.Dimension(140, 100));
        title.setPreferredSize(new java.awt.Dimension(400, 75));
        title.setLayout(new java.awt.BorderLayout());

        signup_title.setBackground(new java.awt.Color(204, 0, 51));
        signup_title.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        signup_title.setForeground(new java.awt.Color(204, 0, 51));
        signup_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_title.setText("SIGNUP");
        signup_title.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 0, 0, 0));
        signup_title.setPreferredSize(new java.awt.Dimension(140, 60));
        title.add(signup_title, java.awt.BorderLayout.CENTER);

        background.add(title);

        middle.setPreferredSize(new java.awt.Dimension(400, 450));
        middle.setLayout(new java.awt.FlowLayout());

        usernamebox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        usernamebox.setMinimumSize(new java.awt.Dimension(250, 20));
        usernamebox.setPreferredSize(new java.awt.Dimension(250, 40));
        usernamebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameboxActionPerformed(evt);
            }
        });

        username_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username_text.setForeground(new java.awt.Color(255, 255, 255));
        username_text.setText("Username");
        username_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        username_text.setPreferredSize(new java.awt.Dimension(250, 40));

        name.setLayer(usernamebox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        name.setLayer(username_text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout nameLayout = new javax.swing.GroupLayout(name);
        name.setLayout(nameLayout);
        nameLayout.setHorizontalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernamebox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(username_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        nameLayout.setVerticalGroup(
            nameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(username_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usernamebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        middle.add(name);

        email_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_text.setForeground(new java.awt.Color(255, 255, 255));
        email_text.setText("Email");
        email_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        email_text.setPreferredSize(new java.awt.Dimension(250, 40));

        email_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email_field.setMinimumSize(new java.awt.Dimension(250, 20));
        email_field.setPreferredSize(new java.awt.Dimension(250, 40));
        email_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email_fieldActionPerformed(evt);
            }
        });

        email.setLayer(email_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        email.setLayer(email_field, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout emailLayout = new javax.swing.GroupLayout(email);
        email.setLayout(emailLayout);
        emailLayout.setHorizontalGroup(
            emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(email_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(email_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        emailLayout.setVerticalGroup(
            emailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(emailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(email_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        middle.add(email);

        phone_number_field.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone_number_field.setMinimumSize(new java.awt.Dimension(250, 20));
        phone_number_field.setPreferredSize(new java.awt.Dimension(250, 40));
        phone_number_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phone_number_fieldActionPerformed(evt);
            }
        });

        phone_number_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        phone_number_text.setForeground(new java.awt.Color(255, 255, 255));
        phone_number_text.setText("Nomor Telepon");
        phone_number_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        phone_number_text.setPreferredSize(new java.awt.Dimension(250, 40));

        nomortelepon.setLayer(phone_number_field, javax.swing.JLayeredPane.DEFAULT_LAYER);
        nomortelepon.setLayer(phone_number_text, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout nomorteleponLayout = new javax.swing.GroupLayout(nomortelepon);
        nomortelepon.setLayout(nomorteleponLayout);
        nomorteleponLayout.setHorizontalGroup(
            nomorteleponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorteleponLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(nomorteleponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phone_number_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone_number_field, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        nomorteleponLayout.setVerticalGroup(
            nomorteleponLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nomorteleponLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phone_number_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(phone_number_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        middle.add(nomortelepon);

        password.setPreferredSize(new java.awt.Dimension(262, 170));

        passwordfield.setPreferredSize(new java.awt.Dimension(250, 40));
        passwordfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordfieldActionPerformed(evt);
            }
        });

        password_text.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_text.setForeground(new java.awt.Color(255, 255, 255));
        password_text.setText("Password");
        password_text.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        password_text.setPreferredSize(new java.awt.Dimension(250, 40));

        show_password_checkbox.setForeground(new java.awt.Color(255, 255, 255));
        show_password_checkbox.setText("Show Password");
        show_password_checkbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_password_checkboxActionPerformed(evt);
            }
        });

        signup_button.setBackground(new java.awt.Color(255, 204, 0));
        signup_button.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signup_button.setForeground(new java.awt.Color(0, 0, 0));
        signup_button.setText("SIGNUP");
        signup_button.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        signup_button.setPreferredSize(new java.awt.Dimension(100, 30));
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        password.setLayer(passwordfield, javax.swing.JLayeredPane.DEFAULT_LAYER);
        password.setLayer(password_text, javax.swing.JLayeredPane.DEFAULT_LAYER);
        password.setLayer(show_password_checkbox, javax.swing.JLayeredPane.DEFAULT_LAYER);
        password.setLayer(signup_button, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout passwordLayout = new javax.swing.GroupLayout(password);
        password.setLayout(passwordLayout);
        passwordLayout.setHorizontalGroup(
            passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordfield, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_text, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(show_password_checkbox))
                    .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordLayout.setVerticalGroup(
            passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(password_text, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(show_password_checkbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        middle.add(password);

        background.add(middle);

        bottom.setPreferredSize(new java.awt.Dimension(400, 75));

        jLabel5.setText("Already have an account?");
        jLabel5.setToolTipText("");

        loginformbutton.setBackground(new java.awt.Color(30, 32, 34));
        loginformbutton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginformbutton.setForeground(new java.awt.Color(255, 204, 0));
        loginformbutton.setText("LOGIN");
        loginformbutton.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0))));
        loginformbutton.setPreferredSize(new java.awt.Dimension(100, 30));
        loginformbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginformbuttonActionPerformed(evt);
            }
        });

        bottom.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bottom.setLayer(loginformbutton, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout bottomLayout = new javax.swing.GroupLayout(bottom);
        bottom.setLayout(bottomLayout);
        bottomLayout.setHorizontalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginformbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        bottomLayout.setVerticalGroup(
            bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomLayout.createSequentialGroup()
                .addGroup(bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(loginformbutton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 45, Short.MAX_VALUE))
        );

        background.add(bottom);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Handles the show password checkbox action.
     * This method toggles the visibility of the password in the password field based on the state of the show password checkbox.
     * @param evt The action event that triggered this method
     */
    private void show_password_checkboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_password_checkboxActionPerformed
        if (show_password_checkbox.isSelected()) {
            passwordfield.setEchoChar((char) 0); // Show password
        } else {
            passwordfield.setEchoChar('*'); // Hide password (you can use '*' as well)
        }
    }//GEN-LAST:event_show_password_checkboxActionPerformed
    /**
     * Handles the action when Enter key is pressed in the password field.
     * This method validates the password against security requirements and
     * triggers the signup button action if the password is valid. If the password
     * does not meet the requirements, an error message is displayed.
     * @param evt The action event that triggered this method
     */
    private void passwordfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordfieldActionPerformed
        String password = new String(passwordfield.getPassword());

        if (!PasswordUtils.isValidPassword(password)) {
            JOptionPane.showMessageDialog(this, "Password must be at least 8 characters long, contain at least an uppercase letter, a lowercase letter, and a number.", "Invalid Password", JOptionPane.ERROR_MESSAGE);
            return; // Stop execution if password is invalid
        }

        signup_buttonActionPerformed(new java.awt.event.ActionEvent(signup_button, ActionEvent.ACTION_PERFORMED, "Enter"));

    }//GEN-LAST:event_passwordfieldActionPerformed
    /**
     * Handles the action when Enter key is pressed in the phone number field.
     * This method moves the focus to the password field when the Enter key is pressed
     * in the phone number field, allowing for quick navigation between fields.
     * @param evt The action event that triggered this method
     */
    private void phone_number_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phone_number_fieldActionPerformed
        passwordfield.requestFocus();
    }//GEN-LAST:event_phone_number_fieldActionPerformed
    /**
     * Handles the action when Enter key is pressed in the email field.
     * This method moves the focus to the phone number field when the Enter key is pressed
     in the email field, allowing for quick navigation between fields.
     * @param evt The action event that triggered this method
     */
    private void email_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email_fieldActionPerformed
        phone_number_field.requestFocus();
    }//GEN-LAST:event_email_fieldActionPerformed
    /**
     * Handles the action when Enter key is pressed in the username field.
     * This method moves the focus to the email field when the Enter key is pressed
     in the username field, allowing for quick navigation between fields.
     * @param evt The action event that triggered this method
     */
    private void usernameboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameboxActionPerformed
        email_field.requestFocus();
    }//GEN-LAST:event_usernameboxActionPerformed
    /**
     * Handles the window closing event.
     * This method opens the Login form when the Signup window is closing,
     * ensuring users can still access the login screen if they decide not to sign up.
     * @param evt The window event that triggered this method
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        new Login().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
     /**
     * Handles the signup button action.
     * This method validates all input fields, checks for duplicate usernames,and creates a new user if all validations pass. It displays appropriate
     * messages for success or failure and opens the Login form on successful signup.
     * The method performs the following validations:
     - Checks that no fields are empty
     - Validates password strength requirements
     - Verifies the username is not already taken
     * @param evt The action event that triggered this method
     */
    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        String username = usernamebox.getText();
        String email = email_field.getText();
        String phone = phone_number_field.getText();
        String password = new String(passwordfield.getPassword());

        if (username.isEmpty() || email.isEmpty() || phone.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "All fields are required!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!PasswordUtils.isValidPassword(password)) {
            JOptionPane.showMessageDialog(this,
                "Password must be at least 8 characters long, contain at least one uppercase letter, one lowercase letter, and one number.",
                "Invalid Password", JOptionPane.ERROR_MESSAGE);
            return;
        }

        UserDAO userDAO = new UserDAO();
        try {
            if (userDAO.usernameExists(username)) {
                JOptionPane.showMessageDialog(this,
                    "Username already exists. Please choose another one.",
                    "Duplicate Username", JOptionPane.ERROR_MESSAGE);
                usernamebox.setText("");
                return;
            }

            if (userDAO.createUser(username, email, phone, password)) {
                JOptionPane.showMessageDialog(this, "Signup successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                new Login().setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Signup failed", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } finally {
            userDAO.closeConnection();
        }
    }//GEN-LAST:event_signup_buttonActionPerformed
    /**
     * Handles the login form button action.
     * This method closes the Signup form and opens the Login form,
     * allowing users to navigate to the login screen if they already have an account.
     * @param evt The action event that triggered this method
     */
    private void loginformbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginformbuttonActionPerformed
        this.dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_loginformbuttonActionPerformed

    /**
     * The main entry point for the application.
     * This method sets up the look and feel, and creates and displays the Signup form.
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLayeredPane bottom;
    private javax.swing.JLayeredPane email;
    private javax.swing.JTextField email_field;
    private javax.swing.JLabel email_text;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton loginformbutton;
    private javax.swing.JLayeredPane middle;
    private javax.swing.JLayeredPane name;
    private javax.swing.JLayeredPane nomortelepon;
    private javax.swing.JLayeredPane password;
    private javax.swing.JLabel password_text;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField phone_number_field;
    private javax.swing.JLabel phone_number_text;
    private javax.swing.JCheckBox show_password_checkbox;
    private javax.swing.JButton signup_button;
    private javax.swing.JLabel signup_title;
    private javax.swing.JLayeredPane title;
    private javax.swing.JLabel username_text;
    private javax.swing.JTextField usernamebox;
    // End of variables declaration//GEN-END:variables
}
